import React, { useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, ScatterChart, Scatter, ZAxis } from 'recharts';
import InfoBubble from '../components/InfoBubble';

function Analytics() {
  const [benchmark, setBenchmark] = useState(null);
  const [loading, setLoading] = useState(false);

  const runBenchmark = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/benchmark');
      const data = await res.json();
      setBenchmark(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  // Mock data for Feature Space Explorer
  const scatterData = [
    { x: 10, y: 30, z: 200, type: 'normal' },
    { x: 30, y: 200, z: 260, type: 'normal' },
    { x: 45, y: 100, z: 400, type: 'normal' },
    { x: 50, y: 400, z: 280, type: 'normal' },
    { x: 70, y: 150, z: 500, type: 'normal' },
    { x: 100, y: 250, z: 200, type: 'normal' },
    { x: 120, y: 100, z: 260, type: 'normal' },
    { x: 170, y: 300, z: 400, type: 'normal' },
    { x: 250, y: 200, z: 280, type: 'normal' },
    { x: 350, y: 150, z: 500, type: 'anomaly' }, // APT
    { x: 380, y: 350, z: 200, type: 'anomaly' }, // APT
    { x: 400, y: 250, z: 260, type: 'anomaly' }, // APT
  ];

  const normalData = scatterData.filter(d => d.type === 'normal');
  const anomalyData = scatterData.filter(d => d.type === 'anomaly');

  // Mock data for Model Latency Comparison
  const latencyData = [
    { name: 'Isolation Forest', cost_ms: 0.12, type: 'Classical' },
    { name: 'Classical SVM', cost_ms: 0.45, type: 'Classical' },
    { name: 'Quantum Kernel (Sim)', cost_ms: 45.2, type: 'Quantum' },
  ];

  return (
    <div>
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 className="page-title">Analytics & Models</h1>
          <p className="page-subtitle">Deep dive into the PCA feature space, quantum vs classical disagreements, and latency metrics.</p>
        </div>
        <button className="btn btn-primary" onClick={runBenchmark} disabled={loading}>
          {loading ? 'Running...' : 'Run Offline Accuracy Check'}
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem', marginBottom: '2rem' }}>
        {/* Feature Space Explorer */}
        <div className="card">
          <h3 style={{ marginTop: 0, display: 'flex', alignItems: 'center' }}>
            Feature Space Explorer (PCA 1 vs PCA 2) <InfoBubble text="A 2D slice of the 4D principal component space generated by the classical preprocessing pipeline." />
          </h3>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
            Visualizing the decision boundary where the QSVM excels at separating non-linear APT features.
          </p>
          <div style={{ height: 300, width: '100%' }}>
            <ResponsiveContainer>
              <ScatterChart margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis type="number" dataKey="x" name="PCA 1" />
                <YAxis type="number" dataKey="y" name="PCA 2" />
                <ZAxis type="number" dataKey="z" range={[60, 400]} />
                <Tooltip cursor={{ strokeDasharray: '3 3' }} />
                <Legend />
                <Scatter name="Normal Telemetry" data={normalData} fill="#3b82f6" />
                <Scatter name="Advanced Threats" data={anomalyData} fill="#ef4444" />
              </ScatterChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Model Latency Panel */}
        <div className="card">
          <h3 style={{ marginTop: 0, display: 'flex', alignItems: 'center' }}>
            Simulation Latency Cost <InfoBubble text="The computational cost to evaluate a single event." />
          </h3>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
            Running a QSVM on a classical statevector simulator introduces a massive latency overhead compared to classical models.
          </p>
          <div style={{ height: 300, width: '100%' }}>
            <ResponsiveContainer>
              <BarChart data={latencyData} layout="vertical" margin={{ top: 20, right: 30, left: 40, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" horizontal={false} />
                <XAxis type="number" dataKey="cost_ms" name="Latency (ms)" unit=" ms" />
                <YAxis type="category" dataKey="name" width={120} />
                <Tooltip cursor={{fill: 'transparent'}} />
                <Legend />
                <Bar dataKey="cost_ms" name="Inference Latency (ms)" fill="#8b5cf6" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div className="card" style={{ marginBottom: '2rem' }}>
        <h3 style={{ marginTop: 0, display: 'flex', alignItems: 'center' }}>
          Quantum vs Classical Disagreement View <InfoBubble text="Events where the models strongly disagreed." />
        </h3>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
          This table surfaces events where the classical SVM classified the telemetry as normal, but the Quantum Kernel detected a high-dimensional anomaly.
        </p>
        <div style={{ overflowX: 'auto' }}>
          <table className="alerts-table">
            <thead>
              <tr>
                <th>Event ID</th>
                <th>Identity</th>
                <th>Classical SVM</th>
                <th>Quantum Kernel</th>
                <th>Delta</th>
                <th>Resolution</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>azure-evt-094122</td>
                <td>svc-shadow-2@corp.local</td>
                <td><span style={{ color: '#10b981', fontWeight: 600 }}>0.12 (Normal)</span></td>
                <td><span style={{ color: '#ef4444', fontWeight: 600 }}>0.89 (Attack)</span></td>
                <td>0.77</td>
                <td>Confirmed True Positive (APT lateral movement)</td>
              </tr>
              <tr>
                <td>aws-evt-019943</td>
                <td>arn:aws:iam::123:user/dev</td>
                <td><span style={{ color: '#10b981', fontWeight: 600 }}>0.31 (Normal)</span></td>
                <td><span style={{ color: '#ef4444', fontWeight: 600 }}>0.74 (Attack)</span></td>
                <td>0.43</td>
                <td>Confirmed True Positive (S3 Bucket Discovery)</td>
              </tr>
              <tr>
                <td>azure-evt-110023</td>
                <td>ops-user-12@corp.local</td>
                <td><span style={{ color: '#ef4444', fontWeight: 600 }}>0.81 (Attack)</span></td>
                <td><span style={{ color: '#10b981', fontWeight: 600 }}>0.22 (Normal)</span></td>
                <td>0.59</td>
                <td>False Positive by Classical (Standard backup script)</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {!benchmark ? null : (
        <div className="card">
          <h3 style={{ marginTop: 0, display: 'flex', alignItems: 'center' }}>
            Offline Benchmark Metrics <InfoBubble text="Evaluation metrics from the latest offline benchmark suite." />
          </h3>
          <div style={{ overflowX: 'auto' }}>
            <table>
              <thead>
                <tr>
                  <th>Detector</th>
                  <th>Detect Rate</th>
                  <th>False Alarms</th>
                  <th>Subtle Attacks</th>
                  <th>Loud Attacks</th>
                  <th>AUC</th>
                  <th>Fit (s)</th>
                  <th>ms/event</th>
                </tr>
              </thead>
              <tbody>
                {benchmark.map((row, i) => (
                  <tr key={i}>
                    <td style={{ fontWeight: 600 }}>{row.name}</td>
                    <td>{(row.detection_rate * 100).toFixed(1)}%</td>
                    <td>{(row.false_positive_rate * 100).toFixed(1)}%</td>
                    <td>{(row.subtle_apt_recall * 100).toFixed(1)}%</td>
                    <td>{(row.loud_attack_recall * 100).toFixed(1)}%</td>
                    <td>{row.roc_auc.toFixed(3)}</td>
                    <td>{row.fit_seconds.toFixed(3)}</td>
                    <td>{row.mean_score_ms.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}

export default Analytics;
